### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tijldeneut**
Hi there, 
I took your beautiful DES to NTLM functions and converted it to a two way script, feel free to just take some snippets or just accept the pull request.

Thank you for some great work

### CODE REVIEW

**Comment by evilmog** [comment]
I am unable to accept your contribution.

This project is MIT licensed. Your code is GPL licensed which is a viral license.

While I appreciate your contribution I cannot accept it unless your code matches the license of the rest of this repo as documented at https://github.com/evilmog/ntlmv1-multi/blob/master/LICENSE and  https://github.com/evilmog/ntlmv1-multi/blob/master/CONTRIBUTING.md

Also I must apologize I forgot to list that requirement in contributing, I have corrected that error.

**Comment by tijldeneut** [comment]
Hi, thank you for your response

If I read your CONTRIBUTING.md file correctly, then the MIT license is also not accepted?

I have no problem with MIT but BSD would be one step too far, I guess.

**Comment by evilmog** [comment]
MIT is the only accepted license sorry I'll go clarify

**Comment by evilmog** [comment]
Corrected to clarify the project license is MIT to match the hashcat
license.

**Pull request closed without merging**
